export const SET_CONCERTS = '@@CONCERTS/SET_CONCERTS';

export const GO_TO_NEXT_CONCERT = '@@CONCERTS/GO_TO_NEXT_CONCERT';
export const GO_TO_PREV_CONCERT = '@@CONCERTS/GO_TO_PREV_CONCERT';

export const SET_COMMENTS_FOR_CONCERT = '@@COMMENTS/SET_COMMENTS_FOR_CONCERT';
export const PREPEND_COMMENT_FOR_CONCERT = '@@COMMENTS/PREPEND_COMMENT_FOR_CONCERT';