export const SET_CONCERTS = '@@CONCERTS/SET_CONCERTS';

export const GO_TO_NEXT_CONCERT = '@@CONCERTS/GO_TO_NEXT_CONCERT';
export const GO_TO_PREV_CONCERT = '@@CONCERTS/GO_TO_PREV_CONCERT';

export const SET_COMMENTS = '@@COMMENTS/SET_COMMENTS';
